Vagrant.configure("2") do |config|
  config.vm.define "server" do |server|
    server.vm.box = "starboard/ubuntu-arm64-20.04.5"
    server.vm.box_version = "20221120.20.40.0"
    server.vm.box_download_insecure = true
    server.vm.provision :shell, path: "../bootstrap.sh"
    server.vm.hostname = "server"
    server.vm.network :private_network, ip: "192.168.101.10"
    server.vm.synced_folder "../", "/home/vagrant/os-challenge-common/"
    server.vm.provider "vmware_desktop" do |v|
      v.ssh_info_public = true
      v.gui = true
      v.linked_clone = false
      v.vmx["ethernet0.virtualdev"] = "vmxnet3"
      v.vmx["ethernet0.pcislotnumber"] = "160"
      v.vmx["memsize"] = "512"
      v.vmx["numbcpus"] = "4"
    end 
  end

  config.vm.define "client" do |client|
    client.vm.box = "starboard/ubuntu-arm64-20.04.5"
    client.vm.box_version = "20221120.20.40.0"
    client.vm.box_download_insecure = true
    client.vm.provision :shell, path: "../bootstrap.sh"
    client.vm.hostname = "client"
    client.vm.network :private_network, ip: "192.168.101.11"
    client.vm.synced_folder "../", "/home/vagrant/os-challenge-common/"
    client.vm.provider "vmware_desktop" do |v|
      v.ssh_info_public = true
      v.gui = true
      v.linked_clone = false
      v.vmx["ethernet0.virtualdev"] = "vmxnet3"
      v.vmx["ethernet0.pcislotnumber"] = "160"
      v.vmx["memsize"] = "512"
      v.vmx["numbcpus"] = "2"
    end 
  end
end